// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./atomic.js'))
  await test.load(import.meta.resolve('./basic.js')) // todo: implement storageInfo API
  await test.load(import.meta.resolve('./batch.js'))
  await test.load(import.meta.resolve('./bit-interlude.js'))
  await test.load(import.meta.resolve('./bitfield.js'))
  await test.load(import.meta.resolve('./clear.js')) // todo: replace Info.bytesUsed API
  // await test.load(import.meta.resolve('./compat.js')) // todo: how to test compat?
  await test.load(import.meta.resolve('./conflicts.js'))
  await test.load(import.meta.resolve('./core.js'))
  await test.load(import.meta.resolve('./encodings.js'))
  await test.load(import.meta.resolve('./encryption.js'))
  await test.load(import.meta.resolve('./extension.js'))
  await test.load(import.meta.resolve('./fully-remote-proof.js'))
  await test.load(import.meta.resolve('./manifest.js'))
  await test.load(import.meta.resolve('./mark-n-sweep.js'))
  await test.load(import.meta.resolve('./merkle-tree.js'))
  await test.load(import.meta.resolve('./merkle-tree-recovery.js'))
  await test.load(import.meta.resolve('./move-to.js'))
  await test.load(import.meta.resolve('./mutex.js'))
  await test.load(import.meta.resolve('./preload.js'))
  // await test.load(import.meta.resolve('./purge.js')) // todo: implement purge
  await test.load(import.meta.resolve('./push.js'))
  await test.load(import.meta.resolve('./remote-bitfield.js'))
  await test.load(import.meta.resolve('./remote-length.js'))
  await test.load(import.meta.resolve('./replicate.js'))
  await test.load(import.meta.resolve('./sessions.js'))
  await test.load(import.meta.resolve('./snapshots.js'))
  await test.load(import.meta.resolve('./streams.js'))
  await test.load(import.meta.resolve('./timeouts.js'))
  await test.load(import.meta.resolve('./user-data.js'))
  await test.load(import.meta.resolve('./wants.js'))

  test.resume()
}
